### ISSUE TITLE
Не могу выполнить git push

### ISSUE THREAD

**Issue by sergey1378** [sergey1378/home-music-training#2]
! [rejected]        new_branch -> new_branch (non-fast-forward)
error: failed to push some refs to 'git@github.com:sergey1378/home-music-training.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by zhabinka** [comment]
Нужно перевести это описание и выполнить рекомендации, которые в нём есть.
